//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_DETAILS
    {
        public string MaHoaDon { get; set; }
        public string MaSanPham { get; set; }
        public short SoLuong { get; set; }
        public double TriGia { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
