//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.INVOICE_DETAILS = new HashSet<INVOICE_DETAILS>();
        }
    
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string Mau { get; set; }
        public string Size { get; set; }
        public double GiaBan { get; set; }
        public int SoLuongTon { get; set; }
        public string TinhTrang { get; set; }
        public string MaLoaiHang { get; set; }
        public string MaBrand { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        public virtual CATEGORIES CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE_DETAILS> INVOICE_DETAILS { get; set; }
    }
}
